@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjYsInVzZXJuYW1lIjoiRGVhbi4xMyIsImlhdCI6MTc3NDkxMjAxNywiZXhwIjoxNzc0OTE1NjE3LCJpc3MiOiJhcHAifQ.ffm1EkWsaK3FqurI56F_j1iDysbgKd3Dnq_wTOaB2sw
DELETE http://localhost:1234/expenses/13
Authorization: Bearer {{token}}
Content-Type: application/json



